### ISSUE TITLE
how to connect the PC over RS485

### ISSUE THREAD

**Issue by Wind06** [Ziyatoe/DTUProController#2]
Hello,

I do have a DTU-pro and DDSU666 from hoymiles connected using the RS485 port .
Are your scripts working with DDSU666 hoymiles or should I use a Standard DDSU666 ?

Can you please also confirm that the following connection is the correct one
- DDUS666 -> DTU-Pro 
- DTU-Pro -> Waveshare Industrial USB to RS485

sorry for such maybe stupid question :-)

Thanks for and help / advice.

**Comment by Ziyatoe** [comment]
hi,
see first https://www.youtube.com/watch?v=IomXSOtnlgg
RS485 is a bus, like a "chain", device connection order doesn't matter

**Comment by Wind06** [comment]
Thanks understood.
