### ISSUE TITLE
Configuration with 2 HM1500 and 1 HM800

### ISSUE THREAD

**Issue by Wind06** [Ziyatoe/DTUProController#3]
Hi again,

In your description you mention one Microinverter MH/MI1500, I am wondering if it can workwith my config
2 Microinverter MH/MI1500 and 1 Microinverter MH/MI800 ?

Or some code modification is required.

Thanks again

**Comment by Ziyatoe** [comment]
hi,
this script is only for ONE microinverter, you can enhanced it your own. since I have no hoymiles, I'm not continue this project

**Comment by Wind06** [comment]
Thanks for your answer, I will try to update hope that I will not break my inverter 😶
But you had Hoymiles to develop this script right ?

one more question the script can either perform zero injection, or just report data from ddsu666. Is my understanding ok ?

thanks spend a good Sunday.

**Comment by Ziyatoe** [comment]
sure I had a MI1500 + DTUpro + DDSU666 for developping.
this script can zeroexport, 
usage: *.py Controller=0/1 [1=controler&datalog] [0=only datalogger], Output=1/0, Limit=10-100
*.py 1 1 50
means, inverter will be limited to 50% with output to console

if you get rid off to this damn DTUPro, you can try https://github.com/lumapu/ahoy

**Comment by Wind06** [comment]
Perfect thanks again

**Comment by Wind06** [comment]
well I received the USB/485 today I enter the following command 
python3 dtupro_ctrl.py 1 1 100
or 
python3 dtupro_ctrl.py 0 1 100

below is what I got, and idea ? 

DTU-Pro RS485/ModbusDTU zero export controller. Version 0.4.0
Limit: 100  OldLimit: 100
MQTT:Connecting to broker  127.0.0.1
MQTT:wait loop
MQTT:connected
Error connecting DTU sernr at 0x2000

I already build an Ahoy which is working correctly, never tried it for zéro injection yet.
Thanks,

**Comment by Ziyatoe** [comment]
edit: 
this script is only for 2.gen inverter like tested MI1500, if you have 3.gen inverter (all HM s) you have to change all adress in dtudtsuregister.json and base adress in script  !!! 
here are the serialnummerbegin for the 2.gen inverter
 0x1020:  return MI300  #MI200,MI300
 0x1021:  return MI300  #MI200,MI300
 0x1040:  return MI600
 0x1041:  return MI600 #MI500,MI600,TSUN TSOL-M800
 0x1060:  return MI1500
 0x1061:  return MI1500 #MI1000,MI1200, MI1500.


--------------------------------------------------------------------------------------------
well, it says clearly that you cant connect to the dtu, 

in script under CONFIGURATION you have to check the setting ports, in script  is for linux:

clientDTU = ModbusSerialClient(
     method='rtu',
     port='/dev/ttyUSB0',        <<<<<<<<<<<  ??????????
     baudrate=9600,
     timeout=8,
     parity='N',
     stopbits=1,
     bytesize=8
)
DTU_DEV_NR = 101                            # Hoymiles DTU-Pro Modbus device number
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
clientDTSU = ModbusSerialClient(
    method='rtu',
    port='/dev/ttyUSB0', <<<<<<<<<<<<<<<<<<<???????
    baudrate=9600,
    timeout=8,
    parity='N',
    stopbits=1,
    bytesize=8
)
DTSU_DEV_NR = 22                            # Chint DTSU666 grid meter Modbus device number

**Comment by Wind06** [comment]
Hello, 

Thanks for your reply, I checked this morning and all seems to be correct

 /dev/ttyUSB0         Future Technology Devices International FT232 Serial (UART) IC

Maybe the USB is not PI4 compatible, I will do more testing and will keep ou posted.

Thanks again for your quick answer / help.

**Comment by Ziyatoe** [comment]
do you have 2.gen inverter? compare the serial nr. first

**Comment by Wind06** [comment]
Good question, I d'ont know I bought it las year "October 2022" it's an Hoymiles compatible one serial number start with 10C 
![IMG_6389](https://github.com/Ziyatoe/DTUProController/assets/64360875/25551f8c-10d3-40e4-b213-7bd2adf31517)

Attached is the picture of it.

**Comment by Wind06** [comment]
Hi you are right I do have 3.gen inverter HM-1500, So I will have to update data accordingly. 

But I guess that my connection problem is not linked not the Serial nulber right ?

**Comment by Ziyatoe** [comment]
HM doesn't work and your USB/RS485 is working if you do not get this error:
"Error connecting client DTU or DTSU"

**Comment by Ziyatoe** [comment]
I changed the script, now for HM and MI inverters, should work for max. 6 inverters.
I can't test it, could you test it?

**Comment by Wind06** [comment]
Hi, sure I will give a try and let you know. Again many thanks for your support

**Comment by Wind06** [comment]
hello, a new test made this morning after a clean install of Raspbian 
I have no chance because the same issue :-( 
I noticed that you updated the dtupro_ctrl.py but not the dtudtsuregister.json ?

python3 dtupro_ctrl.py 1 1 100
DTU-Pro RS485/ModbusDTU zero export controller. Version 0.4.5
Limit: 100  OldLimit: 100
MQTT:Connecting to broker  127.0.0.1
MQTT:wait loop
MQTT:connected
Error connecting DTU sernr at 0x2000
Error connecting DTU sernr at 0x2000
^CTraceback (most recent call last):
  File "dtupro_ctrl.py", line 639, in <module>
    time.sleep(3)
KeyboardInterrupt

**Comment by Ziyatoe** [comment]
this is the error from first read from dtupro, so
I think, you are not connecting the dtupro over rs485, what device number has your dtupro and ddsu666?

**Comment by Wind06** [comment]
Maybe stupide question, but how do you find the device number of DTUpro and ddsu666 ?

**Comment by Ziyatoe** [comment]
so you do not know the device numbers and trying to connect?lol
device numbers are in settings, you should also set the dtupro as remote monitor

**Comment by Wind06** [comment]
Well to be able to do what you suggest, I need an installer account for the DTUpro right ?
Which is not the case today. Can you confirm ?

**Comment by Ziyatoe** [comment]
very clear, if you can not set the dtupro as "remote monitored", which allows to set rs485 device adress, you can not communicate with it

**Comment by Wind06** [comment]
Ok I contacted hoymiles, and they confirm to me that dtupro is set as « remote monitored » as default 
Inverter and DTU don’t have ID number but only serial number. 
can you please explain how you get these IDs this will be more efficient :-)

thanks

**Comment by Ziyatoe** [comment]
oh common!
read the manual
![Screenshot from 2023-11-22 12-42-41](https://github.com/Ziyatoe/DTUProController/assets/108363609/aaff45fe-dfcf-43c5-972b-c2fd96df65d9)

**Comment by Wind06** [comment]
As I told you I only have user access not installer
So I asked them for information. Hope that they will provide it. As soon as received I will restart testing 😉

**Comment by Wind06** [comment]
Hey good news I finally got that number 202, far from the 101 😄 
I will go home and start testing.
I keep you posted

**Comment by Wind06** [comment]
Hello, sorry for the late answer, even with the correct device ID of the DTU-pro and the correct Device ID of the DDSU666
no luck for connection.

So I tried to communicante with DTU-Pro and DDSU666 with a Modbus Application:

I have no issue to communicate with DDSU666 
But I tried to communicate with the same app with the DTU-Pro and the communication cannot be established 👎 
Maybe the remote control has not been set, I will contact them again on Monday, that's very painfull not to have installer account ... grrrrrr

**Comment by Ziyatoe** [comment]
normally, the DTUpro is delivered as "export management" unit, you have to set it as "remote control/modbus"

**Comment by Ziyatoe** [comment]
if you use this as main, you could test the connection with your ddsu:

if __name__ == "__main__":
    # main -------------------------------------------------------------------------------------------------------------

    setupresult=setup_things()

    while not (clientDTSU.connect):
        if Output: print("main: Error connecting client DTU or DTSU")
        #time.sleep(5)

    dtsu =DTSUCtrl()
    while True:#todo try

        dtsu.getData() #get dtsu666 AC data

        if Output: print (boldon,"[main]GridP:", dtsu.GridP," SolarP:",SolarP,boldoff,"do now ZeroExport")


        if Output: print("[main]",datetime.now().strftime('%H:%M:%S'),"----------------------------------sleep ",SLEEP)

        now = datetime.now()
        if now.hour >= 20 or now.hour <= 7: # sleep longer
            time.sleep(60*10)
        else:
            time.sleep(SLEEP)

**Comment by Wind06** [comment]
Thanks again, below is the result, what is strange is that data are empty. by the way for the time being I do have set 0 export on the DTU-pro.

DTU-Pro RS485/ModbusDTU zero export controller. Version 0.4.5
Limit: 100  OldLimit: 100
MQTT:Connecting to broker  127.0.0.1
MQTT:wait loop
MQTT:connected
grid U_ACL1 	 0.0 V
grid I_ACL1 	 0.0 A
grid P_ACtot 	 nan W
grid P_ACL1 	 nan W
grid P_ACL2 	 nan W
grid P_ACL3 	 nan W
				error readFromDataRegList
grid F_AC 	 0.0 Hz
				error readFromDataRegList
grid Q_IMP 	 0.0 kWh
				error readFromDataRegList
grid Q_EXP 	 0.0 kWh
 [main]GridP: nan  SolarP: 0  do now ZeroExport
[main] 10:06:48 ----------------------------------sleep  30

**Comment by Wind06** [comment]
Hello,

Very sorry for the long delay, after 2 weeks discussion with Hoymiles Support I finally get an installer account :-) so I succeed to setup the rs485 port.

I launched the command " python3 dtupro_ctrl.py 0 1 50 " 
The first Inverter HM800 found, second HM1500 found, for the 3rd I got an error. Attached is the log file generated.

Any help will be appreciated as usual.

[SolarZeroinjection.txt](https://github.com/Ziyatoe/DTUProController/files/13527271/SolarZeroinjection.txt)

**Comment by Wind06** [comment]
Hi Ziyatoe, and idea why I can't access the 3 inverter. I am trying to understand why in the .py file, but I am lost ..

[readMiDataRegs] read DTU-Regs 
[readMiDataRegs] Error Port: 3   0x11b8
[readMiDataRegs]cant read DTU-Regs

Thanks

**Comment by Ziyatoe** [comment]
hi, 
I do not check my emails daily,
the script was never tested with more than 1 inverter,
and this version for you, I couldn't test it,  I do not have any hoymiles equipment anymore.
so, I have to go through the script with your log and try to figure out what is wrong,
sorry, it takes time

**Comment by Wind06** [comment]
Thanks for your help, if you don’t have time no problem.  I asked Ahoy team
for an enhancement to support zero injection  with DDSU666.

I really appreciated all your help

Cheers

**Comment by Ziyatoe** [comment]
ich bin mir sicher, dass ahoy team nichts für ddsu666 entwickeln wird, denn ich war bei der entwicklung der ahoy am anfang dabei.
wenn du schon ahoy hast, du kannst ja ddsu666 abfragen (alles im script vorhanden), wie die leistung +/-W ist und dann das ahoy dementsprechend regeln.
somit brauchst du keinen dtu

**Comment by Wind06** [comment]
You are right, the guy from Ahoy who answered to me was not very supportive of this option.
Yes I do have an Ahoy in place which is working perfectly, and you are right I will investigate the way to implément it.

**Comment by Ziyatoe** [comment]
hi
I think, I found the problem, try this V0.4.6

**Comment by Wind06** [comment]
hello, 

ooopsss I tried, now it stops reading inverter 1  

DTU-Pro RS485/ModbusDTU zero export controller. Version 0.4.6
Limit: 100  OldLimit: 100
MQTT:Connecting to broker  127.0.0.1
MQTT:wait loop
MQTT:connected
DTUSerialNr: 0x10f882246532 	Device SN Register List (10F872228412)
MISerialNr : 0x114190556486 	Model: Mi2CH  Ports: 2  Power/Port: 375
MISerialNr : 0x116180400231 	Model: Mi4CH  Ports: 4  Power/Port: 375
MISerialNr : 0x116180400245 	Model: Mi4CH  Ports: 4  Power/Port: 375
Nr of Inv: 3
Inverter 1  of  3  SrNr: 0x114190556486  0x1000 NrOfPorts: 2
[readMiDataRegs] read DTU-Regs 
[readMiDataRegs] readed 
Traceback (most recent call last):
  File "dtupro_ctrl_new.py", line 686, in <module>
    dtu.getData(DTUDataReg, inv, NRofPORTS, invsrnr=InvIdPowr[inv][0])
  File "dtupro_ctrl_new.py", line 552, in getData
    dev_nr=DTU_DEV_NR, number=nrtype)
  File "dtupro_ctrl_new.py", line 272, in readFromDataRegList
    my_result[i] = DtuMiPvData[3].registers[int((adr - dtuDataRegs[3] + i) / 2)]  # PV4
AttributeError: 'int' object has no attribute 'registers'

**Comment by Ziyatoe** [comment]
its difficult for me to check the script without an hoymiles equipment here, but lets try to fix it.
try this version and give me the log

**Comment by Wind06** [comment]
Yes I can imagine, Well with this version the connection is failing immediatly.
Maybe if you have time I can grant you an access to my test raspberry.
Just let me know and I will provide you my email address, if this option could be valid for you

DTU-Pro RS485/ModbusDTU zero export controller. Version 0.4.6.1
Limit: 100  OldLimit: 100
MQTT:Connecting to broker  127.0.0.1
MQTT:wait loop
MQTT:connected
DTUSerialNr: 0x10f882246532 Traceback (most recent call last):
  File "dtupro_ctrl.py", line 663, in <module>
    while not (read_sernr()):
  File "dtupro_ctrl.py", line 166, in read_sernr
    if Output: print("DTUSerialNr:", hex(int(DtuId)), "\tDevice SN Register List (L\u0130KE:10F8xxxxxxxx)")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0130' in position 27: ordinal not in range(256)

**Comment by Ziyatoe** [comment]
was für ein system hast du, windows? der fehler sagt, dass dein system  'latin-1' unicode nicht encoden kann, eigenartig!
ich habe die zeile geaendert, probiere nochmals

**Comment by Wind06** [comment]
My system is a PI4 with raspbian Buster installed. I can try with another environment or setup the unix system differently.

**Comment by Ziyatoe** [comment]
ok, just try it

**Comment by Wind06** [comment]
Attached the log, still and issue reading the 3rd inverter data 
[DTUlog.txt](https://github.com/Ziyatoe/DTUProController/files/13627211/DTUlog.txt)

**Comment by Ziyatoe** [comment]
ok, I hope, I see the problem now, gonna try to fix it

**Comment by Ziyatoe** [comment]
sunday work ;-) try this one and give me the log 
please check the power from each inverter, if total power is approx. ok

**Comment by Wind06** [comment]
"sunday work", indeed yes and sorry for that, result attached.

Reported data seems to be accurate 

[getData]>>>>>>>> this inverter: 0x114190556486  total  86.9  W
[getData]>>>>>>>> this inverter: 0x116180400231  total  152.8  W
[getData]>>>>>>>> this inverter: 0x116180400245  total  149.0  W

[DTUlog.txt](https://github.com/Ziyatoe/DTUProController/files/13627874/DTUlog.txt)

But after sleep---30 when it start again to pool  data I get error reading DTU stuff

**Comment by Wind06** [comment]
attached is the MQTT Data, a lot of informations are coming with zero as value.

![Capture d’écran 2023-12-10 à 15 14 47](https://github.com/Ziyatoe/DTUProController/assets/64360875/aad324f9-de3a-4c2d-973f-8fb200f01424)

and after the first sleep 30 ---- I do have a lot of [DtuDtsuCtrl]Cant read DTU All Registers!!

**Comment by Wind06** [comment]
I confirm that inverters data are read once, and data are accurate. 
Then when trying to read data again, the following error is displayed.

[main]GridP: 0.0  SolarP: 364.4  do now ZeroExport
[main](abs)GridP: 0.0  is in doZEROSensivity: 16
[main] 15:41:54 ----------------------------------sleep  30
Inverter 1  of ^[[1m 3  SrNr: 0x114190556486 ^[[0m basis: 0x11e0 0x1190 NrOfPorts: 2
[readMiDataRegs] read DTU-Regs
[readMiDataRegs] Error Port: 1   0x11b8
[readMiDataRegs]cant read DTU-Regs
[DtuDtsuCtrl]Cant read DTU All Registers!!
[readMiDataRegs] read DTU-Regs
[readMiDataRegs] Error Port: 0   0x1190
[readMiDataRegs] Error Port: 1   0x11b8
[readMiDataRegs]cant read DTU-Regs
.....

**Comment by Ziyatoe** [comment]
ok, getting closer with inverter! I missed one line, now its in, try it, now we should  get all inverters/ports in each iteration.
the other issue is your dtsu666, it seems to be, that the data registers are not compatible with, what I have in dtudtsuregisters.json under "directory": "grid". you have to check that with your manual.

**Comment by Ziyatoe** [comment]
you can comment the line 709,  without dtsu to check only the inverters.
and use:
python dtupro_ctrl.py 0 1

**Comment by Wind06** [comment]
Hello, I will do testing tomorrow, for inverter only. 

For dtsu666 I noticed this already I will check and compare mine with information you have and will do some testing on my side.

many thanks for all your help, we will succeed :-)
Good evening.

**Comment by Ziyatoe** [comment]
dtsu666: it can be also the rs485 modbus adress, you have to check it aswell, in code it is DTSU_DEV_NR = 22

**Comment by Wind06** [comment]
Hi, I tested inverter today and all seems to be ok, the loop is working and reported data accurate.
Now I will focus on DDSU666 to find out correct registers, the DTSU_DEV_NR  is alrady set correctly on my side.

**Comment by Ziyatoe** [comment]
good news!
so, you can comment the line 261 for better output view.
are you able to check the mqtt data aswell?

**Comment by Ziyatoe** [comment]
> Hi, I tested inverter today and all seems to be ok, the loop is working and reported data accurate. Now I will focus on DDSU666 to find out correct registers, the DTSU_DEV_NR is alrady set correctly on my side.

on the market, there are many dtsu666, I was using the orig. CHINT DTSU666

**Comment by Wind06** [comment]
> good news! so, you can comment the line 261 for better output view. are you able to check the mqtt data aswell?

mqtt data are also ok, below is the output of mqtt explorer

![Capture d’écran 2023-12-12 à 10 20 06](https://github.com/Ziyatoe/DTUProController/assets/64360875/edf82d51-2f5c-4deb-9bbd-3a7dd3eeb398)

**Comment by Wind06** [comment]
> CHINT DTSU666

mine is also a CHINT but a DDSU666 single phase not DTSU666, now I  need to find the correct modbus addresses.
and update the json file accordingly.

**Comment by Wind06** [comment]
I found the registers for DDSU666

  0x2000,   // DDSU666_VOLTAGE             [V]
  0x2002,   // DDSU666_CURRENT             [A]
  0x2004,   // DDSU666_POWER               [KW]
  0x2006,   // DDSU666_REACTIVE_POWER      [KVAR]
  0x200A,   // DDSU666_POWER_FACTOR
  0x200E,   // DDSU666_FREQUENCY           [Hz]
  0X4000,   // DDSU666_IMPORT_ACTIVE       [kWh]
  0X400A,   // DDSU666_EXPORT_ACTIVE       [kWh]

I am currently modifying the dtudtsuregister.json but do have some issues with ratio I guess ... trying to get correct information back from the module

**Comment by Wind06** [comment]
Ok if my understanding is correct a DTSU is 3 Phase when DDSU is single phase
 My DDSU

  0x2000,   // DDSU666_VOLTAGE             [V]
  0x2002,   // DDSU666_CURRENT             [A]
  0x2004,   // DDSU666_POWER               [KW] "Instant Total Active Power"
  0x2006,   // DDSU666_REACTIVE_POWER      [KVAR] 
  0x2008   // DDSU666_APPARENT_POWER
  0x200A,   // DDSU666_POWER_FACTOR
  0x200E,   // DDSU666_FREQUENCY           [Hz]
  0X4000,   // DDSU666_POSITIVE_ACTIVE_TOTAL_ENERGY       [kWh]

Attached the modified register file 
[dtudtsuregister.json](https://github.com/Ziyatoe/DTUProController/files/13649143/dtudtsuregister.json)

I can it now all reported data seems to be correct, but I have a doubt I don't need P_ACL2 and 3 right because I have a signe phase. am I correct ?

grid U_ACL1 	 228.7 V
grid I_ACL1 	 2.4 A
grid P_ACtot 	 -0.2 W
grid P_ACL1 	 0.0 W
grid P_ACL2 	 0.5 W
grid P_ACL3 	 -0.3 W
grid F_AC 	 50.0 Hz
grid Q_IMP 	 170.9 kWh
grid Q_EXP 	 2822.8 kWh
 [main]GridP: -0.15649999678134918  SolarP: 0  do now ZeroExport
[main] 15:36:27 ----------------------------------sleep  30

**Comment by Ziyatoe** [comment]
we need only the total grid power from gridmeter, also in dtudtsuregister.json, it is the "P_ACtot", which is in your case the 0x2000
now,  I am wondering how DTUpro will  limiting more than one inverter

**Comment by Wind06** [comment]
> we need only the total grid power from gridmeter, also in dtudtsuregister.json, it is the "P_ACtot", which is in your case the 0x2000 now, I am wondering how DTUpro will limiting more than one inverter

you mean 0x2004 :-) but is it normal that with the script I get a " **grid P_ACtot 	 -0.6 W** " which is negative and only 0.6W when I am getting 630W from the grid ?

**Comment by Ziyatoe** [comment]
> > we need only the total grid power from gridmeter, also in dtudtsuregister.json, it is the "P_ACtot", which is in your case the 0x2000 now, I am wondering how DTUpro will limiting more than one inverter
> 
> you mean 0x2004 :-) but is it normal that with the script I get a " **grid P_ACtot -0.6 W** " which is negative and only 0.6W when I am getting 630W from the grid ?

you have to choose right nr of bytes in that register and ratio, depend on your ddsu, also the nrtype (8 is 32bitFloat):
 {"title": "P_ACtot", "adr": "0x2012", "count": 2, "ratio": 10, "nrtype":8,"unit": "W"},

**Comment by Wind06** [comment]
Hello, sorry for not coming back earlier, but weather was not so good for a real testing.
Apparently not working in my configuration even if traces shows that zero is setup. inverters are not updated.

Python3 dtupro_ctrl.py 1 1 50 

 [main]GridP: -1.0952999591827393  SolarP: 1869.7999999999997  do now ZeroExport
[main](abs)GridP: 1.0952999591827393  is in doZEROSensivity: 16
[main] 11:29:02 ----------------------------------sleep  30

**Comment by Ziyatoe** [comment]
this is when script thinks its night time, then will be no updates, is you clock ok?
comment the lines:724,725,726 and try again

**Comment by Wind06** [comment]
Hello, yes clock is correct I guess output of date command jeudi 21 d?cembre 2023, 12:32:24 (UTC+0100)

Attached 2 files one **
[log_DDSU666_Day.txt](https://github.com/Ziyatoe/DTUProController/files/13740839/log_DDSU666_Day.txt)
[log_DDSU666_Night.txt](https://github.com/Ziyatoe/DTUProController/files/13740838/log_DDSU666_Night.txt)**

_**During night**_

 [main]GridP: -0.43810001015663147  SolarP: 0.0  do now ZeroExport
[main]invPortSTS_DC: 0  not doing doZeroExport
[main] 18:23:32 ----------------------------------sleep  30

**And during day:**

_**If no Zero is required**_
[main]GridP: -0.35040000081062317  SolarP: 1360.9  do now ZeroExport
[main](abs)GridP: 0.35040000081062317  is in doZEROSensivity: 16
[main] 12:04:01 ----------------------------------sleep  30

_**If Zero is required**_
 [main]GridP: 0.05119999870657921  SolarP: 1441.6  do now ZeroExport
[main](abs)GridP: 0.05119999870657921  is in doZEROSensivity: 16
[main] 12:10:44 ----------------------------------sleep  30

**Comment by Ziyatoe** [comment]
sorry, but you should give me the logs in a file and write on the top how your command line was! "python dtupro_ctrl.py...."
otherwise I have no chance to guess what you are doing.
the limit parameter in command line, is the first time limiting in %, should be normal 100

ok, in those 2 log files, I don't see a problem, it does what it should, dc and ac powers are correct, in daytime doing zeroexport, in night time not.
on the other hand, doing zeroexport is not that easy as you would mine, did you set the pramaeters exactly what your system needs? 
check this in script:
  MAXPOWER  = 2000     # Watt, total all inverters   to be SET !!
  EXPORT_PLUS = 1  # gridmeter direction  (-)=0 ,  (+)=1
  doZEROSensivity = 16  # do_zeroexort if more than this power needed


the MIxxx inverters can not be limited under 10% of total power!! the script setting is for MIxxx inverters!
the HMxxx inverters can be limited up to 2% of total power, so you have to play with:
      Limit10P = 125  # change to 10% under this watt
      Limit11P = 170  # over this watt is fine limiting with +/- 1

**Comment by Ziyatoe** [comment]
If Zero is required
[main]GridP: 0.05119999870657921 SolarP: 1441.6 do now ZeroExport
mainGridP: 0.05119999870657921 is in doZEROSensivity: 16
[main] 12:10:44 ----------------------------------sleep 30

gridP is 0.05W!! also it ist between doZEROSensivity 16W
also it is correct!

**Comment by Ziyatoe** [comment]
in your log:
something is wrong here
grid U_ACL1 	 217.1 V
grid I_ACL1 	 2.2 A
grid P_ACtot 	 -0.4 kWh
grid P_ACL1 	 -0.0 W
grid P_ACL2 	 0.5 W
grid P_ACL3 	 -0.9 W
grid F_AC 	 50.0 Hz
grid Q_IMP 	 177.0 kWh
grid Q_EXP 	 2891.7 kWh
 [main]GridP: -0.4334999918937683  SolarP: 1038.2  do now ZeroExport
 
 UAC*IAC=477W >>>  GridP: -0.433499W ??????

**Comment by Ziyatoe** [comment]
in your log:
something is wrong here
grid U_ACL1 	 217.1 V
grid I_ACL1 	 2.2 A
grid P_ACtot 	 -0.4 kWh
grid P_ACL1 	 -0.0 W
grid P_ACL2 	 0.5 W
grid P_ACL3 	 -0.9 W
grid F_AC 	 50.0 Hz
grid Q_IMP 	 177.0 kWh
grid Q_EXP 	 2891.7 kWh
 [main]GridP: -0.4334999918937683  SolarP: 1038.2  do now ZeroExport
 
grid P_ACtot should be in Watt!!
 UAC*IAC=477W >>>  GridP: -0.433499W ??????

**Comment by Wind06** [comment]
Ok thanks for your answer, the DDSU666 report the "**_P_ACtot 	 0.8 kWh_**"
To have the value in W I need to *1000 ans the result is _**828W**_
So I modified the .py file and now zero injection is called and working 

The command used is **_python3 dtupro_ctrl.py 1 1 50_**

 **_[main]GridP: 814.7000074386597  SolarP: 2047.1  do now ZeroExport
[doZeroExport] 2047.1 61 16
				Limit calculated %: 61
				zu viel  Limit is 60 old  61
				Limiting new 60 % old 61 % target 1232.4
				writing DTU 1 time 0x9d9d 60 101
				DTU writeOK WriteRegisterResponse 40349 => 60_** 

........

**_[main]GridP: 780.9000015258789  SolarP: 2021.4  do now ZeroExport
[doZeroExport] 2021.4 50 16
				Limit calculated %: 62
				zu viel  Limit is 49 old  50
				Limiting new 49 % old 50 % target 1240.5
				writing DTU 1 time 0x9d9d 49 101
				DTU writeOK WriteRegisterResponse 40349 => 49_**

I really  appreciate all your help and advice, I guess that we can close this topic :-)

Merry Christmas

**Comment by Ziyatoe** [comment]
very nice!
thank you for testing
